# data.py

HEALTH_DATABASE = {
    "Alzheimer's Disease": {
        "summary": "Best preventative measures are good, deep sleep, excercise, and mentally stimulating activities.",
        "nutrients": [
            {"factor": "B Vitamins (Folate, B6, B12)",
                "impact": "Limited evidence that B vitmamins/Folate help slow/prevent dementia, it is associated with slowing cognitive decline."},
            {"factor": "Magnesium",
                "impact": "Most people have healthy levels of magnesium. Defiiceny is linked to a 36% risk increase and excesssive levels increase risk by 30%."},
            {"factor": "Pottasium",
                "impact": "Some evidence to show that a higher intake of pottasium decreases odds of cognitive impairment, most people are pottasium defficient."},
        ],
        "actions": [
            {"factor": "Sleep Well",
                "impact": "20-45% lower risk with 150minutes of activity. Improves blood flow to brain, supports brain cell surivvival, and lowers chronic inflammation."},
            {"factor": "Excercise",
                "impact": "~30-40% lower risk of dementia compared to people that sleep <6 hours. Helps the brain clear out toxic byproducts."},
            {"factor": "Mentally Stimulating Activities",
                "impact": "5 year delayed onset of alzheimers with high levels of cognitive activity compared to low activity."},
        ],
        "risks": [
            {"factor": "Smoking",
                "impact": "40% higher risk due to sustained lack of oxygen in brain (nicotine/carbon monoxide) and combustion products cause oxidative stress and inflammation"},
            {"factor": "Excessive Alcohol",
                "impact": "Excessive alcohol increases risk significantly due to decreased brain volume/white matter, restricted blood flow, depleteing B1 vitamin, and oxidative stress"},
        ],
    },
    "Arthritis": {
        "summary": "A broad name for conditions that cause inflammation, swelling, and pain in joints/connective tissues.",
        "nutrients": [
            {"factor": "Monounsaturated Fats (healthy fats)",
                "impact": "Lowers systemic inflammation examples are olive oil, avocados, and nuts."},
            {"factor": "Omega-3s",
                "impact": "Act in a similiar way to monounsaturated fats, come from fatty fish, nuts, or plant oils (canola, soybean, etc.)."},
            {"factor": "Fiber",
                "impact": "Decreases inflammation, comes from oats, brown rice, whole grains."},
            {"factor": "Antioxidants",
                "impact": "Slows/decreases downstream cartilage breakdown, chronic inflammatoin, and joint tissue death. Eat your fruits/vegetables."},
        ],
        "actions": [
            {"factor": "sleep well",
                "impact": "Helps the brain clear out toxic byproducts, regular <6 hours/night results in ~30-40% higher risk of dementia "},
            {"factor": "excersize",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
        ],
    },
    "Heart Disease": {
        "summary": "A range of conditions that affect the heart, often linked to plaque buildup in the arteries.",
        "nutrients": [
            {"factor": "B Vitamins (Folate, B6, B12)",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "Magnesium",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "Pottasium",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "Deep Sleep",
                "impact": "Essential for the glymphatic system to clear out amyloid-beta plaques from the brain."}
        ],
        "actions": [
            {"factor": "sleep well",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "excersize",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "Pottasium",
                "impact": "Helps lower homocysteine levels, an amino acid linked to brain atrophy and increased Alzheimer's risk."},
            {"factor": "Deep Sleep",
                "impact": "Essential for the glymphatic system to clear out amyloid-beta plaques from the brain."}
        ],
    },
}

SUBSTANCE_DATABASE = {
    "Nicotine": {
        "summary": "Central nervous system stimulant, vasoconstrictor (shrinks blood vessels)",
        "nutrients": [
            {"factor": "Mental",
                "impact": "Can improve SHORT term mood, focus, and congnitive function."},
            {"factor": "Hunger",
                "impact": "Supresses hunger"},
            {"factor": "Parkinson reduction",
                "impact": "Reduces chance of Parkinsons inversly with how many years you smoked, 40 years ~46% reduction and 9 years leads to ~8% reduction"},
            {"factor": "Ulcerative Colitis",
                "impact": "Decreases inflammatory T-cell response so smokers have a lower incidence of IBD"},
            {"factor": "Endometrial and Estrogen-Dependent Cancers",
                "impact": "Smoking breaks down estrogen so postmenopausal women who smoke have a 30-40% reduced risk of developing endometrial cancer, endometrioid/clear-cell ovarian cancers, and uterine fibroids"},
            {"factor": "Preeclampsia Reduction (NOT SAFE)",
                "impact": "Pregnant women WHO SMOKE have a 30-50% less chance for preeclampsia."},
        ],
        "actions": [
            {"factor": "Addiction",
                "impact": "Extremely addictive and tolerance builds quickly."},
            {"factor": "Back Pain and Shorter Height",
                "impact": "Reduced blood flow cuases spinal disks dry out causing shrinking and herniated disks."},
            {"factor": "Vision Loss",
                "impact": "Speeds up age-related macular degeneration (extremely prevalent) because retina blood vessels don't get enough blood"},
            {"factor": "Sex Worsens",
                "impact": "Causes short term erectile dysfunction in men and reduced arousal/sensation in women,"},
            {"factor": "Slows Cut/Surgery Healing",
                "impact": "Cuts, bones, and scraped all need blood to heal"},
            {"factor": "Sking aging (wrinkles)",
                "impact": "Narrowed blood vessels reduce collagen production causing sagging, facial wrinkles, and a grey complexion"},
            {"factor": "Memory Problems <- (AND DEMENTIA)",
                "impact": "Of course your brian needs blood so brain tissue is starved over time leading to memory loss and [vascular dementia]"},
            {"factor": "Hair Thinning/Graying",
                "impact": "Same logic, less blood/oxygen, thins and falls out more"},
            {"factor": "Receding Gums",
                "impact": "Same thing, no blood = receded gums and it masks gum disease (bleding) until it is severe "},
            {"factor": "Kidney Damage",
                "impact": "KINEYS NEED BLOOD in a very delicate complex way so nicotine messes them up"},
            {"factor": "Hearing Loss",
                "impact": "Exact same as kidneys"},
            {"factor": "Missing Some Other Effects",
                "impact": "You might be expecting something like cancer, take a look at the Smoking section because this section only covers the effects of the nioctine itself"},
            {"factor": "When Pregnant:",
                "impact": "Smoking during pregnancy increases the risk of placental abruption, intrauterine growth restriction (IUGR), low birth weight, sudden infant death syndrome (SIDS), and stillbirth."},
        ],
    },
    "Smoking (anything)": {
        "summary": "Combustion Products ie any smoke you inhale",
        "nutrients": [
            {"factor": "Mental",
                "impact": "Can improve SHORT term mood, focus, and congnitive function."},
            {"factor": "Hunger",
                "impact": "Supresses hunger"},
        ],
        "actions": [
            {"factor": "Addiction",
                "impact": "Extremely addictive and tolerance builds quickly."},
            {"factor": "Back Pain and Shorter Height",
                "impact": "Reduced blood flow cuases spinal disks dry out causing shrinking and herniated disks."},
            {"factor": "Vision Loss",
                "impact": "Speeds up age-related macular degeneration (extremely prevalent) because retina blood vessels don't get enough blood"},
            {"factor": "Sex Worsens",
                "impact": "Causes short term erectile dysfunction in men and reduced arousal/sensation in women,"},
            {"factor": "Slows Cut/Surgery Healing",
                "impact": "Cuts, bones, and scraped all need blood to heal"},
            {"factor": "Sking aging (wrinkles)",
                "impact": "Narrowed blood vessels reduce collagen production causing sagging, facial wrinkles, and a grey complexion"},
            {"factor": "Memory Problems <- (AND DEMENTIA)",
                "impact": "Of course your brian needs blood so brain tissue is starved over time leading to memory loss and [vascular dementia]"},
            {"factor": "Hair Thinning/Graying",
                "impact": "Same logic, less blood/oxygen, thins and falls out more"},
            {"factor": "Receding Gums",
                "impact": "Same thing, no blood = receded gums and it masks gum disease (bleding) until it is severe "},
            {"factor": "Kidney Damage",
                "impact": "KINEYS NEED BLOOD in a very delicate complex way so nicotine messes them up"},
            {"factor": "Hearing Loss",
                "impact": "Exact same as kidneys"},
            {"factor": "Missing Some Other Effects",
                "impact": "You might be expecting something like cancer, take a look at the Smoking section because this section only covers the effects of the nioctine itself"},
        ],
    }
}
